services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-enq}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-enq}
      POSTGRES_DB: ${POSTGRES_DB:-enq}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-enq} -d ${POSTGRES_DB:-enq}"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api:
    # GHCR:
    # image: ghcr.io/sirclappington/enq-api:latest
    # Docker Hub:
    image: sirclappington/enq-api:latest
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DSN: postgres://${POSTGRES_USER:-enq}:${POSTGRES_PASSWORD:-enq}@postgres:5432/${POSTGRES_DB:-enq}?sslmode=disable
      REDIS_ADDR: redis:6379
      API_ADDR: :8080
      # TZ: America/New_York
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Optional healthcheck ONLY if your binary supports it (distroless has no shell):
    # healthcheck:
    #   test: ["CMD", "/enq", "health"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 10

  scheduler:
    # GHCR:
    # image: ghcr.io/sirclappington/enq-scheduler:latest
    # Docker Hub:
    image: sirclappington/enq-scheduler:latest
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      POSTGRES_DSN: postgres://${POSTGRES_USER:-enq}:${POSTGRES_PASSWORD:-enq}@postgres:5432/${POSTGRES_DB:-enq}?sslmode=disable
      REDIS_ADDR: redis:6379
      # TZ: America/New_York
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  pgdata: {}
  redisdata: {}
