version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: enq
      POSTGRES_PASSWORD: enq
      POSTGRES_DB: enq
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  api:
    build: .
    command: ["go", "run", "./cmd/api"]
    env_file: [.env]
    environment:
      POSTGRES_DSN: postgres://enq:enq@postgres:5432/enq?sslmode=disable
      REDIS_ADDR: redis:6379
    depends_on: [postgres, redis]
    ports: ["8080:8080"]

  scheduler:
    build: .
    command: ["go", "run", "./cmd/scheduler"]
    env_file: [.env]
    environment:
      POSTGRES_DSN: postgres://enq:enq@postgres:5432/enq?sslmode=disable
      REDIS_ADDR: redis:6379
    depends_on: [postgres, redis]

  web:
    build:
      context: ./web
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8080
    ports: ["3000:3000"]

volumes:
  pgdata: {}
