blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/sirclappington/enq/security/advisories/new
    about: Please report security issues privately via a security advisory.
  - name: Questions & Support
    url: https://github.com/sirclappington/enq/discussions
    about: Use Discussions for Q&A, ideas, and general help.
