name: ci
on: [push, pull_request]
jobs:
test:
runs-on: ubuntu-latest
services:
postgres:
image: postgres:16
env:
POSTGRES_USER: enq
POSTGRES_PASSWORD: enq
POSTGRES_DB: enq
ports: ['5432:5432']
options: >-
--health-cmd "pg_isready -U enq" --health-interval 10s --health-timeout 5s --health-retries 5
redis:
image: redis:7
ports: ['6379:6379']
steps:
- uses: actions/checkout@v4
- uses: actions/setup-go@v5
with: { go-version: '1.22' }
- name: Install goose
run: go install github.com/pressly/goose/v3/cmd/goose@latest
- name: Migrate
env:
POSTGRES_DSN: postgres://enq:enq@localhost:5432/enq?sslmode=disable
run: ./scripts/migrate.sh
- name: Test
run: go test ./...